### ISSUE TITLE
Fix the anchor tags link 

### ISSUE THREAD

**Issue by GouthamV10** [Nulsoft/Nulsoft#16]
In file index.html
in line 152 and 1174 
there are two href links, these links are not working while clicking on them but are redirecting when opened in a new tab. Fix this issue
respective js and css files are in repo

Note : Please fork and work in v1 branch only

**Comment by pandey22** [comment]
Hii Goutham , can you please explain your issue briefly on what the desired changes need to be , because as per my interpretation , the line 152 link works fine , is it that you want the links to get opened in a new tab ?

**Comment by GouthamV10** [comment]
hi pandey thanks for looking into it .
Yes the links need to be opened in new tab. Also the code seems fine but doesn't work when run locally or during deployment.

**Comment by GouthamV10** [comment]
closed
